/**
 * URL generation utilities for the vacation management app
 */

const CANONICAL_BASE = 'https://starsvacationmanagementv2.vercel.app';

function isLocalUrl(u?: string | null): boolean {
  if (!u) return true;
  return u.includes('localhost') || u.includes('127.0.0.1') || u.includes('0.0.0.0');
}

function canonicalize(u: string): string {
  let url = u.replace(/\/$/, '');
  if (url.includes('stars-vacation-management.vercel.app')) {
    url = url.replace('stars-vacation-management.vercel.app', 'starsvacationmanagementv2.vercel.app');
  }
  return url;
}

/**
 * Base URL for links embedded in EMAILS. These must always be publicly
 * reachable, so any localhost value is rejected — even when an email is
 * generated by a local dev server (where APP_BASE_URL / NEXTAUTH_URL point to
 * localhost). Falls back to the canonical production domain.
 */
export function getEmailBaseUrl(): string {
  const candidates = [
    process.env.EMAIL_BASE_URL,
    process.env.PRODUCTION_BASE_URL,
    process.env.APP_BASE_URL,
    process.env.NEXT_PUBLIC_APP_URL,
    process.env.NEXTAUTH_URL,
    process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : undefined,
  ];
  for (const c of candidates) {
    if (c && !isLocalUrl(c)) return canonicalize(c);
  }
  return CANONICAL_BASE;
}

export function getBaseUrl(): string {
  // First check for explicit production URL override
  const productionUrl = process.env.PRODUCTION_BASE_URL || process.env.APP_BASE_URL;
  if (productionUrl) {
    const url = productionUrl.replace(/\/$/, '');
    // Ensure we always use the canonical domain
    if (url.includes('stars-vacation-management.vercel.app')) {
      return url.replace('stars-vacation-management.vercel.app', 'starsvacationmanagementv2.vercel.app');
    }
    return url;
  }

  // Check Vercel environment variables for production
  const v = process.env.VERCEL_URL; // bare host like my-app.vercel.app
  if (v) {
    const url = v.startsWith('http') ? v : `https://${v}`;
    // Ensure we always use the canonical domain
    if (url.includes('stars-vacation-management.vercel.app')) {
      return url.replace('stars-vacation-management.vercel.app', 'starsvacationmanagementv2.vercel.app');
    }
    return url;
  }

  // Check NEXTAUTH_URL but avoid localhost in production
  const nextAuthUrl = process.env.NEXTAUTH_URL;
  if (nextAuthUrl && !nextAuthUrl.includes('localhost')) {
    const url = nextAuthUrl.replace(/\/$/, '');
    // Ensure we always use the canonical domain
    if (url.includes('stars-vacation-management.vercel.app')) {
      return url.replace('stars-vacation-management.vercel.app', 'starsvacationmanagementv2.vercel.app');
    }
    return url;
  }

  // For local dev or when no production URL is available, return empty string
  // Call sites should handle this appropriately
  return '';
}

export function absoluteUrl(path: string): string {
  const base = getBaseUrl();
  return base ? `${base}${path.startsWith('/') ? path : '/' + path}` : path;
}

// The following builders are used for links embedded in emails — they always
// use getEmailBaseUrl() so they can never point to localhost.

export function adminVacationRequestUrl(id: string, locale = 'en'): string {
  return `${getEmailBaseUrl()}/${locale}/admin/vacation-requests/${id}`;
}

export function vacationRequestUrl(id: string, locale = 'en'): string {
  return `${getEmailBaseUrl()}/${locale}/vacation-request/${id}`;
}

export function adminDashboardUrl(locale = 'en'): string {
  return `${getEmailBaseUrl()}/${locale}/admin`;
}

export function vacationRequestFormUrl(locale = 'en'): string {
  return `${getEmailBaseUrl()}/${locale}/vacation-request`;
}

